### ISSUE TITLE
Initial draw is different?

### ISSUE THREAD

**Issue by JensNordenbro** [JeremyKuhne/RedrawPerformance#2]
I don't know if this belongs here but too me the inital draw on all controls, especially seen on DataGridView is much slower (multiple paints / flickering) on the .NET5 variants. 

ManyControls for example also flickers more. 

Do you experience this too?

**Comment by JeremyKuhne** [comment]
The code here is contrived (refreshing many, many times) to help get a more accurate view the allocation differences and it isn't using double buffering so flickering is expected. Rendering is actually faster which makes the flickering more noticeable.
